### ISSUE TITLE
英文系统无法使用的问题

### ISSUE THREAD

**Issue by hyne-shan** [pingfangx/TranslatorX#11]
我用的是英文系统，我把作者的resource，和lib中的_en进行了替换，可以汉化了，建议作者做一个整合包

**Comment by pingfangx** [comment]
你好，在
 [4.3 汉化包放入 lib 中之后，汉化没有生效](https://github.com/pingfangx/TranslatorX#43-汉化包放入-lib-中之后汉化没有生效)
中提到了这个问题，以前是支持英文操作系统的，但是在解决 #7 的时候进行了修改，是为了方便不需替换的汉化包直接使用，如果有需要，以后可能会添加直接替换的汉化包。

**Comment by pingfangx** [comment]
你好，感谢之前的建议，目前已经添加了 resources_en.jar 的汉化包，如果需要可以下载。
