### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by playbear** [pingfangx/TranslatorX#12]
![image](https://user-images.githubusercontent.com/8079857/37667600-56e45c00-2c9d-11e8-9e27-2f0b4ffad71a.png)

**Comment by pingfangx** [comment]
你好，你是想问这个菜单没有汉化吗？
汉化包对主程序使用的 resources_en.jar  进行了完整的汉化，但是有部分菜单没有使用标准的国际化方式读取资源（这需要修改源文件），或者使用插件的形式加载（这需要汉化插件的资源包），所以有一部分内容没有进行汉化。
