### ISSUE TITLE
希望能出clion的汉化包

### ISSUE THREAD

**Issue by zhanun** [pingfangx/TranslatorX#13]
感谢您的努力，一直使用您的汉化！最近使用clion，发现您还没有这方面的汉化，但是目前使用pycharm的汉化包用于clion，没有发现异常，可以正常工作，希望能出clion的汉化包。最后再次感谢您的付出和努力！

**Comment by pingfangx** [comment]
已添加，欢迎使用，有问题可以再反馈。

**Comment by zhanun** [comment]
非常感谢！！
