### ISSUE TITLE
idea2018版本汉化以后发现的问题

### ISSUE THREAD

**Issue by 214024475** [pingfangx/TranslatorX#14]
我发现汉化以后   Preferences点击没有反应

**Comment by 1247884082** [comment]
感谢楼主的贡献

**Comment by pingfangx** [comment]
你好，经过测试，最新 2018.1.4 版本的 idea 配 cn 汉化包 resources_cn_IntelliJIDEA_2018.1_r2.jar  
是可以正常使用的，请尝试，如果有问题可以追问。
