### ISSUE TITLE
使用汉化包后 Tomcat加载web项目会失败

### ISSUE THREAD

**Issue by LilithBristol** [pingfangx/TranslatorX#16]
- Java 9
- Idea 2018.1
- Tomcat 9

在使用Tomcat启动一个spring web项目时 会报错
```java
Configuration error
java.io.FileNotFoundException: F:\DevelopmentKitApplication\JetBrain\index\.IntelliJIdea2018.1\system\tomcat\Î´ÃüÃû_springmultienvconfig\conf\logging.properties (系统找不到指定的路径。)
```

经检查 是tomcat的运行实例目录出现了中文路径的原因
idea会自动在...\.IntelliJIdea2018.1\system\tomcat目录下
建立一个Tomcat的catalina_base实例
形如 Unamed_{项目名}
在我的项目中就是
> 未命名_springmultienvconfig

然后把tomcat配置文件复制过去

因为此处是中文路径 所以复制失败 导致访问不到文件
启动项目也失败了

可以通过更改 项目下的.idea\workspace.xml下配置项来规避此问题
```xml
  <server-settings>
        <option name="BASE_DIRECTORY_NAME" value="未命名_springmultienvcpnfig" />
   </server-settings>
```
去掉"未命名_springmultienvcpnfig"中未命名就不会有中文路径了

这应该算是jetbrain的问题？没考虑到非ASCII字符路径的转换😏
汉化包使其暴露了出来

不过以JB的尿性 大概是不会改的🙄
作者君看看能否改下

**Comment by LilithBristol** [comment]
有些地方没汉化 看到作者也说明了理由
强迫症犯了 自己fork了下 想看看能补充不
怎么改编码格式都是 这种乱码

```
analysis.scope.title={0} \u8303\u56f4
scope.option.whole.project=\u6574\u4e2a\u9879\u76ee(&P)
```
作者能告诉下怎么打开这个项目不😂

**Comment by pingfangx** [comment]
已记录，可能是因为把 Unamed_ 直接汉化为 未命名，下个版本会改一下。
编码的转换请查看 [native2ascii](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/native2ascii.html)

**Comment by pingfangx** [comment]
另外项目是用 [OmegaT](http://omegat.org/) 打开的，软件会自动进行编码的转换，只需查看内容与翻译即可。
