### ISSUE TITLE
pycharm汉化后设置不可用

### ISSUE THREAD

**Issue by minchangchen** [pingfangx/TranslatorX#19]
windwos10系统   pycharm版本为2018.1

**Comment by pingfangx** [comment]
你好，当版本不对应时，设置有可能会无法打开。请下载对应的软件及汉化包 2018.1，只有 .1 没有其他，请不要使用 2018.1.4 或其他版本。

**Comment by minchangchen** [comment]
我下载的就是对应得版本额 <...>Translat...>PyCharm>2-替换 lib...>2018.1>，请问你们测试的时候是好的嘛？

**Comment by minchangchen** [comment]
好吧，了解了，那你知道无法使用设置的原因吗？

**Comment by pingfangx** [comment]
你好，原因是设置里面有某个资源没有汉化，或者汉化不兼容，导致打开设置时读取资源失败，就打开失败了。
你是使用哪个版本的软件打开开的，可以查看错误信息，里面会显示哪里出错了。
