### ISSUE TITLE
请问能增加Rider的汉化包么

### ISSUE THREAD

**Issue by wgjas2** [pingfangx/TranslatorX#20]
请问能增加Rider的汉化包么

**Comment by pingfangx** [comment]
你好，你可以尝试下载其他软件的汉化包，一样放到 lib 中即可实现汉化了。  
大部分内容是通用的汉化，少部份软件专有的内容可能会缺少汉化。

**Comment by zdlIsIcePig** [comment]
大锅 增加个Rider的汉化包呗
