### ISSUE TITLE
GoLand2018.1汉化后设置不可用

### ISSUE THREAD

**Issue by AloneZy** [pingfangx/TranslatorX#22]
GoLand版本为2018.1，汉化包版本为resources_cn_GoLand_2018.1_r2
关闭当前项目可以打开设置，但是有些设置项显示一直在加载，如编辑器设置某个语言子目录

**Comment by pingfangx** [comment]
你好，当版本校大变化时，设置可能会出现异常。  
经测试 2018.1 使用 resources_cn_GoLand_2018.1_r2.jar，可以正常打开设置，我对 Go 不太熟悉，您指的
“设置某个语言子目录”是在哪里，我操作的截图如下。  
如果还有问题，请补充或等待 2018.2 版本的更新。
![设置截图](https://user-images.githubusercontent.com/12677730/42410638-6f54a498-821f-11e8-9180-245b36d337c0.png)

**Comment by transtone** [comment]
请问 2018.2 的版本更新什么时候可以下载？
