### ISSUE TITLE
idea 2018.2直接放入lib的版本好像失效

### ISSUE THREAD

**Issue by luciouskami** [pingfangx/TranslatorX#25]
idea 2018.2直接放入lib的版本好像失效，AS的话又更新到新版本了，旧版本的放入lib的版本也失效。

**Comment by pingfangx** [comment]
测试是没有问题的，请提供你放的位置截图，或加群反馈。

**Comment by luciouskami** [comment]
![shoot](https://user-images.githubusercontent.com/10268785/43991104-ed9ad41a-9d97-11e8-9c6f-aeeee878a2cd.png)
放在安装目录下的lib里面位置没错吧。。

**Comment by pingfangx** [comment]
放的地方没有问题，打开是还是英文吗？操作系统是中文吧？可以直接加群Q我。

**Comment by luciouskami** [comment]
是的，操作系统是中文。我加下群吧。。这个问题比较诡异，我以前明明用的好好的。

**Comment by luciouskami** [comment]
解决了。
