### ISSUE TITLE
请问下如果as的版本是3.1.4可以用3.1.3的汉化包吗？

### ISSUE THREAD

**Issue by hankuksui** [pingfangx/TranslatorX#30]
首先感谢大神！做了这么多工作，有些地方汉化一下确实很方便。
问题如题，如果这样做了，然后如果有问题的话，移除汉化jar包会恢复吗？

**Comment by hankuksui** [comment]
刚才试了下，确实可以，很多地方都汉化了~再次谢谢大神
我想问下大神，汉化这个是不是把resources_en里面的内容改成中文就行了啊？

**Comment by pingfangx** [comment]
是的，可以参见常见问题里的汉化原理。

**Comment by hankuksui** [comment]
好的谢谢
