### ISSUE TITLE
android studio 3.2.1 不支持

### ISSUE THREAD

**Issue by youngjuning** [pingfangx/TranslatorX#33]
使用 3.1.* 汉化后，设置打不开

**Comment by pingfangx** [comment]
请查看 [设置打不开](https://github.com/pingfangx/TranslatorX/wiki/FAQ#%E8%AE%BE%E7%BD%AE%E6%89%93%E4%B8%8D%E5%BC%80)
还有问题请追问。

**Comment by youngjuning** [comment]
@pingfangx thx for your great work
