### ISSUE TITLE
关于汉化中能否作者信息在同一行显示

### ISSUE THREAD

**Issue by buildyuan** [pingfangx/TranslatorX#37]
![img](https://user-images.githubusercontent.com/31715808/48758563-6c135780-ecdb-11e8-8edd-e27fb06883f2.png)
我的显示器是1920x1080
能否复现这个问题呢？

**Comment by pingfangx** [comment]
你好，这里是因为前面的“——————”的引起的。
如果删除“——————”，汉化作者也不会显示在同一行，而是会拼接在 JetBrains s.r.o 后面（添加换行符也无效）。
下一个版本我会再研究一下，争取可以换行，感谢使用，感谢反馈。

**Comment by pingfangx** [comment]
感谢反馈，已修改，AndroidStudio 3.3 同步了此更改。
其他软件将会在 v2019.1 中更改。
