### ISSUE TITLE
发现语法检查的放大镜出现乱码

### ISSUE THREAD

**Issue by Andy095** [pingfangx/TranslatorX#43]
如图所示，发现语法检查的放大镜出现乱码。切换回英文显示正常
![image](https://user-images.githubusercontent.com/41384519/51513331-41fa2500-1e45-11e9-92b7-7c029d28a1a6.png)

**Comment by pingfangx** [comment]
你好，经测试正常，可能是使用的字体有问题，请切换字体试一下。
[切换方法](https://github.com/pingfangx/TranslatorX/wiki/FAQ#%E6%B1%89%E5%AD%97%E4%B9%B1%E7%A0%81%E4%B8%AD%E6%96%87%E6%98%BE%E7%A4%BA%E4%B8%BA%E6%A1%86%E6%A1%86)

**Comment by Andy095** [comment]
测试了3台主机还是，问题都一样。 我们使用的是最新版本2018.3
![qq 20190122135923](https://user-images.githubusercontent.com/41384519/51515357-542c9100-1e4e-11e9-9748-e2ec30207616.jpg)
![qq 20190122140006](https://user-images.githubusercontent.com/41384519/51515358-542c9100-1e4e-11e9-9fb4-a623388e8084.jpg)

**Comment by pingfangx** [comment]
不好意思，无法重现您的问题。
以下是我的环境截图，请检查一下软件版本、java 版本等，如果有发现问题欢迎继续反馈。
* 显示效果
![image](https://user-images.githubusercontent.com/12677730/51541760-9c6ea200-1e94-11e9-96f2-076a4ddc9060.png)
* 软件版本
![image](https://user-images.githubusercontent.com/12677730/51541918-00916600-1e95-11e9-9bba-eb73a65d2066.png)
* java 版本
![image](https://user-images.githubusercontent.com/12677730/51541899-f40d0d80-1e94-11e9-8e58-e2d33b70917a.png)
* 字体设置
![image](https://user-images.githubusercontent.com/12677730/51541948-0edf8200-1e95-11e9-864b-11f5871d6d43.png)

**Comment by Andy095** [comment]
![image](https://user-images.githubusercontent.com/41384519/51575027-4da02700-1eeb-11e9-9565-165b2a5fc22f.png)
已经定位到问题

**Comment by pingfangx** [comment]
感谢反馈，我的一直是默认设置，所以没注意到这个问题。
