### ISSUE TITLE
Android Studio 3.3 和 DataGrip

### ISSUE THREAD

**Issue by charliezzo** [pingfangx/TranslatorX#45]
Android Studio 3.3 用 3.2.1 的汉化包有很多地方翻译不了，另外求作者大大出 DataGrip 的汉化包。

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/52609332-dc371100-2eb7-11e9-84ce-e7986854ceef.png)

**Comment by pingfangx** [comment]
刚放假回来，不要着急哈，会更新的。

**Comment by pingfangx** [comment]
AndroidStudio 更新了 3.3，3.3.1 与 3.3 完全兼容。
DataGrid 请关注 #40 。

**Comment by youngjuning** [comment]
@pingfangx 感谢
