### ISSUE TITLE
这是汉化失败了么，都是乱码？

### ISSUE THREAD

**Issue by Nicholas2014** [pingfangx/TranslatorX#5]
![qq 20180111101457](https://user-images.githubusercontent.com/9709321/34805395-e1a8e2cc-f6b8-11e7-8b98-d47d26c354dc.png)
![qq 20180111101733](https://user-images.githubusercontent.com/9709321/34805397-e1d978d8-f6b8-11e7-8ad5-96c67aa54079.png)

**Comment by pingfangx** [comment]
可能是当前字体不支持中文显示，请删除汉化包，尝试下列操作，如果有问题请追问。
 File → Settings → Appearance & Behavior → Appearance →
勾选 Override default fonts by (not recommended): 选择 Microsoft YaHei 或者其他显示为框框的中文字体。

**Comment by Nicholas2014** [comment]
现在好了 没看到后面的说明
