### ISSUE TITLE
建议根据jetbrains官方Help进行汉化

### ISSUE THREAD

**Issue by CoKoOne** [pingfangx/TranslatorX#50]
jetbrains Help官网，里面有对IntelliJ IDEA每一个功能的详细说明，访问该官网，然后用浏览器插件翻译整个网页，加上自己的理解进行一些中文本地语义的修改，进行汉化，可能比光从软件的简短英文描述进行汉化准确先。

IntelliJ IDEA  Help的官网：

[https://www.jetbrains.com/help/idea/installation-guide.html?section=Windows](url)

该官网打开时间较长，需要20秒左右。

**Comment by pingfangx** [comment]
用了好几年的软件，绝大多数功能都是有使用或了解的，不了解的功能在翻译时都有查询官方帮助的，比如 Breadcrumbs 、gutter 之类的。
每一条翻译都是人工翻译的，机器翻译只是参考哟，在使用过程中见到翻译不好的地方也在不断修改，有觉得翻译不准确的地方可以提出来，比如哪里哪里应该翻译成什么比较好，这样下一个版本就会直接修改的。
