### ISSUE TITLE
作者大大 我的提交还没合并么

### ISSUE THREAD

**Issue by LilithBristol** [pingfangx/TranslatorX#51]
是有什么问题需要改进么

**Comment by pingfangx** [comment]
不好意思，之前已经在[这里回复](https://github.com/pingfangx/TranslatorX/pull/47#issuecomment-471813109)了呢，同时希望亲可以[加群交流](https://www.pingfangx.com/xx/translation/jetbrains/feedback/qqgroup)哦。
因为后续直接更新并翻译了2019.1，所以就没有合并，但也非常感谢您的劳动成果。
如果有贡献翻译的意愿，后续可能考虑出一份贡献说明。
* 只更新季度版本，不更新小版本（小版本的修改可以在本地累积，季度版本发时更新源文并将累积的修改 pull request）。
* 修改前请保持与源仓库同步，你是在 fork 基础上修改的，已经落后于源仓库，没有及时同步冲突会比较多。
* 切换 develop 并在其上修改，修改后提交 pull request。仅将翻译修改内容提交至 develop，更新时会统一合到 master。
* 只需要提交 project_save.tmx 的修改即可，其他内容不需提交（源文件会在季度版本发布时统一更新）。
* 翻译时注意格式化。

**Comment by LilithBristol** [comment]
哦哦 这样啊 
确实有些地方没注意到

以后得加群交流了
