### ISSUE TITLE
关于汉化无法生效

### ISSUE THREAD

**Issue by StevenByte** [pingfangx/TranslatorX#52]
用的系统是Parrot，理论基于Debian，装上Clion之后汉化包不生效，无论作何调整都是英文...

**Comment by pingfangx** [comment]
请参阅 [wiki-汉化不生效](https://github.com/pingfangx/TranslatorX/wiki/FAQ#%E6%B1%89%E5%8C%96%E4%B8%8D%E7%94%9F%E6%95%88)
可能是因为语言环境不是中文，可以在 vmoptions 中配置
-Duser.language=zh
-Duser.region=CN
如果还有问题可以在可加群反馈。
