### ISSUE TITLE
MacBook idea debug下无法正常显示 touch bar快捷键

### ISSUE THREAD

**Issue by yuxiang88327** [pingfangx/TranslatorX#53]
估计是汉化把debugger窗口汉化为“调试” 但是在设置中菜单和工具栏里touchbar配置的目录仍为debugger 所导致的
![image](https://user-images.githubusercontent.com/23050512/61855180-2eae3c00-aef2-11e9-9a40-26f0b66c7a28.png)
![image](https://user-images.githubusercontent.com/23050512/61855226-44236600-aef2-11e9-999e-b3f7a87495a5.png)

**Comment by pingfangx** [comment]
好的，感谢反馈，新版本会修改一下。如果可以，欢迎加群，到时候修改了可以帮忙测一下。

**Comment by pingfangx** [comment]
感谢反馈，已更新，请下载查看是否已解决。

**Comment by yuxiang88327** [comment]
> 感谢反馈，已更新，请下载查看是否已解决。

已解决！

**Comment by alterem** [comment]
m1 上依旧没有解决
