### ISSUE TITLE
JetBrains ReSharper C++ 能汉化个吗

### ISSUE THREAD

**Issue by taodaqiao** [pingfangx/TranslatorX#55]
JetBrains ReSharper C++ 能汉化吗

**Comment by pingfangx** [comment]
你好，如果有3个人要求就会加入汉化。  
如果暂时没有，可以使用其他任何一个软件的汉化包，大体上是通用的。

**Comment by LeoZhu3018116** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by icls1337** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by pqsworld** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by taodaqiao** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by icls1337** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by PingXD** [comment]
同求resharper加入汉化

**Comment by 954187350** [comment]
> 请求ReSharper加入汉化。谢谢

**Comment by wind-talk** [comment]
请求ReSharper加入汉化。谢谢

**Comment by yy007668** [comment]
同求汉化！

**Comment by c4sku7** [comment]
同求resharper C++ 加入汉化

**Comment by wf0206** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingfangx/TranslatorX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 晚上7:48
收件人:&nbsp;"pingfangx/TranslatorX"<TranslatorX@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [pingfangx/TranslatorX] JetBrains ReSharper C++ 能汉化个吗 (#55)





 
同求resharper C++ 加入汉化

**Comment by soarteam** [comment]
同求resharper加入汉化

**Comment by Aloento** [comment]
同求resharper加入汉化

**Comment by DPXir** [comment]
请求 ReSharper 加入汉化

**Comment by QiDianMaker** [comment]
同求 ReSharper 加入汉化

**Comment by zlyy178** [comment]
同求 ReSharper 加入汉化

**Comment by shakyun** [comment]
同求 ReSharper 加入汉化

**Comment by nameishyl** [comment]
请求 ReSharper 加入汉化。谢谢

**Comment by Vincent11499** [comment]
请求 ReSharper 加入汉化。谢谢
