### ISSUE TITLE
能否添加 Rubymine 的支持

### ISSUE THREAD

**Issue by chenjau** [pingfangx/TranslatorX#6]
你好, 非常感谢你的工作. 
能否添加 Rubymine 的汉化支持?
[Rubymine](https://www.jetbrains.com/ruby/)

**Comment by pingfangx** [comment]
你好，可以的，我会在周末抽时间更新，请等待。

**Comment by pingfangx** [comment]
你好，已经更新了 RubyMine 2017.3.2 的汉化包，请下载测试。

**Comment by chenjau** [comment]
非常感谢!

**Comment by pingfangx** [comment]
不客气，如果有问题可以继续提问。
