### ISSUE TITLE
webstorm ubuntu18.04不可用

### ISSUE THREAD

**Issue by hznuksco** [pingfangx/TranslatorX#61]
把下下来的文件丢进lib了，重启无用

**Comment by pingfangx** [comment]
仔细阅读 [使用帮助](https://github.com/pingfangx/TranslatorX/wiki/FAQ#%E6%B1%89%E5%8C%96%E4%B8%8D%E7%94%9F%E6%95%88)，lib 中是否有 resources_en.jar
或者加群反馈。

**Comment by hznuksco** [comment]
昨天下的github上的。按理说github上的和百度网盘的应该是一样的。但是我后面换成百度云盘的就行了
