### ISSUE TITLE
如何自己来修改汉化文件

### ISSUE THREAD

**Issue by xxbetta** [pingfangx/TranslatorX#66]
有些地方没有汉化,我想在原有的基础上来增加没有汉化的地方!

这个工作改怎么来做!

谢谢提供的汉化, 已经star

**Comment by pingfangx** [comment]
请查看 [Contributing](https://www.pingfangx.com/xx/translation/jetbrains/feedback/contributing)
不过马上要出官方的插件了，可以考虑向官方插件贡献。
