### ISSUE TITLE
2020.1.1版什么时候可以出汉化呢

### ISSUE THREAD

**Issue by YYZZAA** [pingfangx/TranslatorX#70]
大佬辛苦啦，能有汉化的软件真是帮大忙了，超级感谢！
想知道什么时候会更新2020.1.1版的汉化，或者有没有继续更新的打算，因为2020.1.1版的CLion在用2019版的汉化包的时候是汉化不完全的

**Comment by JamesWynnReal** [comment]
同问

**Comment by 820Reverse** [comment]
@YYZZAA @bizwofficial 
2020之后的版本，官方支持汉化了，插件里面搜chinese，安装重启就行了。

**Comment by YYZZAA** [comment]
> @YYZZAA @bizwofficial
> 2020之后的版本，官方支持汉化了，插件里面搜chinese，安装重启就行了。

已经找到了，多谢！
