### ISSUE TITLE
放进去之后全是乱码啊

### ISSUE THREAD

**Issue by yangcongs** [pingfangx/TranslatorX#8]

**Comment by yangcongs** [comment]
我用的3.0

**Comment by pingfangx** [comment]
是显示为方框吗？如果不是，请截图补充，如果是，请参见
4.2 汉化后中文显示为框框

当前字体不支持中文显示，请到 File → Settings → Appearance & Behavior → Appearance →
勾选 Override default fonts by (not recommended): 选择 Microsoft YaHei 或者其他显示为框框的中文字体。

**Comment by yangcongs** [comment]
嗯嗯 就是显示为框框 按大佬的指示已经改好了 谢谢大佬
