### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by eGluZl** [pingfangx/TranslatorX#9]
![image](https://user-images.githubusercontent.com/20966488/36070378-e587fce6-0f33-11e8-9925-9c259f55c679.png)

**Comment by pingfangx** [comment]
你好，菜单及其他地方是否显示正常，请尝试 #8 中的解决方案，如果不行，请补充电脑系统，软件版本，jdk版本，谢谢。

**Comment by pingfangx** [comment]
不好意思，我升级了 jdk 和 2017.3.4 没有办法重现你的问题，不知道是否跟你本地的 jdk 或字体有关。

**Comment by pingfangx** [comment]
根据 #43 ，请尝试修改编辑器 > Font
